cloud:
  aws:
    region:
      static: "us-east-1"

signer.script: "C:/Users/alejandro/Documents/git/Signer/sign-metadata.sh"
spring:
  autoconfigure:
    exclude:
      - org.springframework.cloud.aws.autoconfigure.context.ContextInstanceDataAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextStackAutoConfiguration
      - org.springframework.cloud.aws.autoconfigure.context.ContextRegionProviderAutoConfiguration